"""empty message

Revision ID: 14e6e2698c14
Revises: 35eb47f6f800
Create Date: 2016-04-17 11:55:23.959262

"""

# revision identifiers, used by Alembic.
revision = '14e6e2698c14'
down_revision = '35eb47f6f800'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('appointment', sa.Column('is_new', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'is_new')
    op.drop_column('appointment', 'created_at')
    ### end Alembic commands ###
