"""empty message

Revision ID: 1dcbc2351f6c
Revises: 4fe87ff585e9
Create Date: 2016-04-16 16:07:52.505197

"""

# revision identifiers, used by Alembic.
revision = '1dcbc2351f6c'
down_revision = '4fe87ff585e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agency', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agency')
    ### end Alembic commands ###
