"""empty message

Revision ID: 222b37097bf5
Revises: 3151cf6eaaa0
Create Date: 2016-04-17 18:37:18.567547

"""

# revision identifiers, used by Alembic.
revision = '222b37097bf5'
down_revision = '3151cf6eaaa0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
