"""empty message

Revision ID: 22d7e1dba8c7
Revises: 222b37097bf5
Create Date: 2016-05-15 16:34:51.598040

"""

# revision identifiers, used by Alembic.
revision = '22d7e1dba8c7'
down_revision = '222b37097bf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'updated_at')
    ### end Alembic commands ###
