"""empty message

Revision ID: 3151cf6eaaa0
Revises: 4845f0eb74f1
Create Date: 2016-04-17 14:01:37.993443

"""

# revision identifiers, used by Alembic.
revision = '3151cf6eaaa0'
down_revision = '4845f0eb74f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
