"""empty message

Revision ID: 35eb47f6f800
Revises: 1dcbc2351f6c
Create Date: 2016-04-16 16:36:46.316903

"""

# revision identifiers, used by Alembic.
revision = '35eb47f6f800'
down_revision = '1dcbc2351f6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('agency', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    ### end Alembic commands ###
