"""empty message

Revision ID: 37164e7e3fde
Revises: 22d7e1dba8c7
Create Date: 2016-05-15 17:45:20.961562

"""

# revision identifiers, used by Alembic.
revision = '37164e7e3fde'
down_revision = '22d7e1dba8c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('reserved_date', sa.Date(), nullable=True))
    op.add_column('appointment', sa.Column('reserved_hour', sa.Time(), nullable=True))
    op.drop_column('appointment', 'updated_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_column('appointment', 'reserved_hour')
    op.drop_column('appointment', 'reserved_date')
    ### end Alembic commands ###
