"""empty message

Revision ID: 4202df29a849
Revises: 37907ce52504
Create Date: 2016-05-15 19:23:56.709784

"""

# revision identifiers, used by Alembic.
revision = '4202df29a849'
down_revision = '37907ce52504'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_logout', sa.DateTime(), nullable=True))
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'last_logout')
    op.drop_column('users', 'last_login')
    op.add_column('appointment', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###
