"""empty message

Revision ID: 4323b1658305
Revises: 4202df29a849
Create Date: 2016-05-15 19:37:50.831703

"""

# revision identifiers, used by Alembic.
revision = '4323b1658305'
down_revision = '4202df29a849'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_login', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'appointment', 'updated_at')
    op.drop_column(u'users', 'last_logout')
    op.drop_column(u'users', 'last_login')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.add_column(u'users', sa.Column('last_logout', sa.DATETIME(), nullable=True))
    op.add_column(u'appointment', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_table('user_activity')
    ### end Alembic commands ###
