"""empty message

Revision ID: 458168fb98fd
Revises: bddcd99a47c
Create Date: 2016-06-11 14:02:42.490570

"""

# revision identifiers, used by Alembic.
revision = '458168fb98fd'
down_revision = 'bddcd99a47c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('cif', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'cif')
    ### end Alembic commands ###
