"""empty message

Revision ID: 45d0c48c5bee
Revises: 4323b1658305
Create Date: 2016-05-15 21:00:16.054858

"""

# revision identifiers, used by Alembic.
revision = '45d0c48c5bee'
down_revision = '4323b1658305'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_day', sa.Date(), nullable=True),
    sa.Column('last_day', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.add_column(u'users', sa.Column('last_logout', sa.DATETIME(), nullable=True))
    op.add_column(u'appointment', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_table('user_vacancy')
    ### end Alembic commands ###
