"""empty message

Revision ID: 4fe87ff585e9
Revises: 2d540a4bff11
Create Date: 2016-04-16 15:47:52.881902

"""

# revision identifiers, used by Alembic.
revision = '4fe87ff585e9'
down_revision = '2d540a4bff11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agency_name', 'agency', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agency_name', 'agency')
    op.drop_table('agency')
    ### end Alembic commands ###
