"""empty message

Revision ID: 535d8646105b
Revises: 458168fb98fd
Create Date: 2016-06-11 14:21:21.650921

"""

# revision identifiers, used by Alembic.
revision = '535d8646105b'
down_revision = '458168fb98fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_vacancy', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_vacancy', 'status')
    ### end Alembic commands ###
