"""empty message

Revision ID: bddcd99a47c
Revises: 45d0c48c5bee
Create Date: 2016-05-18 08:44:51.073783

"""

# revision identifiers, used by Alembic.
revision = 'bddcd99a47c'
down_revision = '45d0c48c5bee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cif', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('registration_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_cif', 'company', ['cif'], unique=True)
    op.create_index('ix_company_name', 'company', ['name'], unique=False)
    op.create_index('ix_company_registration_id', 'company', ['registration_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.add_column(u'users', sa.Column('last_logout', sa.DATETIME(), nullable=True))
    op.add_column(u'appointment', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.drop_index('ix_company_registration_id', 'company')
    op.drop_index('ix_company_name', 'company')
    op.drop_index('ix_company_cif', 'company')
    op.drop_table('company')
    ### end Alembic commands ###
